### ISSUE TITLE
Failed to Parse Worldgen

### ISSUE THREAD

**Issue by Frzncore** [Ametrin-Studios/DungeonsEnhanced#24]
**Describe the bug**
****************** Blame Report Worldgen Import 1.16.5-3.7.0-forge ******************

 Failed to parse worldgen. This can be tricky to solve but it could be from using a value that is over a hardcoded limit.
 Here's some info to help narrow down where and what could be the broken worldgen element.

 Error msg is: Value 9 outside of range [0:7]
 Parent Affected: ResourceKey[minecraft:worldgen/configured_structure_feature / dungeons_enhanced:monster_maze] | net.minecraft.world.gen.feature.StructureFeature@33001dd9

 Partial JSON Result: {
  "config": {
    "start_pool": "dungeons_enhanced:monster_maze/root",
    "size": 9
  },
  "type": "dungeons_enhanced:monster_maze"
}
[18:14:53] [main/ERROR]: Error adding element: Value 9 outside of range [0:7]
[18:14:55] [main/ERROR]: 

**Version Info:**
 - Minecraft version: [e.g. 1.16.5]
 - Forge version [e.g. 36.2.35]
 - Structure Gel API version [e.g. 1.7.8]
 - Dungeons Enhanced version [e.g. 1.7]

**Comment by BarionLP** [comment]
does it crash?
I thought this limit was introduced in 1.18.2
