### ISSUE TITLE
Any plans to add a mod to Modrinth?

### ISSUE THREAD

**Issue by Alter73** [Ametrin-Studios/DungeonsEnhanced#48]
Hi! I just make quite a lot of modpacks in the Modrinth launcher and a lot of mods have moved there. It is also possible because the service is developed only for Minecraft. It would be much more convenient if Dungeons Enhanced mod was also in Modrinth, otherwise I have to download it separately for each modpack and check for its updates, but this is very inconvenient when creating modpacks. It would be nice if such a cool mod could be downloaded from the second most popular Minecraft modding site. Plus, Structure Gel API is already available in Modrinth, so there won't be any problems with the mod.

**Comment by BarionLP** [comment]
pls do a minimum amount of research in the future
https://modrinth.com/mod/dungeons-enhanced

**Comment by Alter73** [comment]
Oh, sorry, I didn't notice right away, I was just looking at the author's nickname when I was looking for the mod. I apologize again.
